[versions]
agp = "8.11.2"
androidx-lifecycle = "2.10.0"
composeMultiplatform = "1.10.3"
kotlin = "2.3.20"
kotlinx-coroutines = "1.10.2"
kotlin-logging = "8.0.4"
logback = "1.5.34"
logstash = "9.0"
material3 = "1.10.0-alpha05"
spotless = "8.6.0"
detekt = "2.0.0-alpha.3"

[libraries]
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging"}
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback"}
logstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
