config:
  validation: false
  warningsAsErrors: true
  checkExhaustiveness: true

console-reports:
  active: true
  exclude: []

style:
  active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
  BracesOnWhenStatements:
    active: true
  CascadingCallWrapping:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  DoubleNegativeExpression:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExpressionBodySyntax:
    active: true

comments:
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true
  UndocumentedPublicFunction:
    active: true

complexity:
  CognitiveComplexMethod:
    active: true
  ComplexInterface:
    active: true
  CyclomaticComplexMethod:
    active: true
  LabeledExpression:
    active: true
  LargeClass:
    active: true
  LongMethod:
    active: true
  LongParameterList:
    active: true
  NestedScopeFunctions:
    active: true
  StringLiteralDuplication:
    active: true
  TooManyFunctions:
    active: true

exceptions:
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  ThrowingExceptionInMain:
    active: true

naming:
  BooleanPropertyNaming:
    active: true
  FunctionNameMaxLength:
    active: true
  FunctionNameMinLength:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  VariableMaxLength:
    active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable

performance:
  CouldBeSequence:
    active: true
  UnnecessaryInitOnArray:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: true

potential-bugs:
  Deprecation:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  ExitOutsideMain:
    active: true
  ImplicitUnitReturnType:
    active: true
  MissingUseCall:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  UnnamedParameterUse:
    active: true
  UnnecessaryNotNullCheck:
    active: true
