name: CI

on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v6

      - name: Настройка JVM
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Настройка Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Проверка форматирования
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v6

      - name: Настройка JVM
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Настройка Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Сборка
        run: ./gradlew build
